import type { Metadata } from "next";
import { Geist, Geist_Mono, Outfit } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/lib/theme-provider";
import { Toaster } from "@/components/ui/sonner";
import { NuqsAdapter } from "nuqs/adapters/next/app";
import { SimpleNavBAr } from "@/components/custom/Navbar/SimpleNavBar";
import { QueryProvider } from "@/lib/React-Query-Wrapper";
import { getWebsiteDetails } from "@/actions/webisteDetails";
const outfit = Outfit({ subsets: ["latin"], variable: "--font-sans" });

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const data = await getWebsiteDetails();
  /*  console.log("webiste data", data); */
  return (
    <html lang="en">
      <body className={`${outfit.variable} antialiased`}>
        <QueryProvider>
          <ThemeProvider
            attribute="data-theme"
            defaultTheme={data.themeColor ?? "light"}
            disableTransitionOnChange
            enableColorScheme
            themes={[
              "light",
              "dark",
              "blue",
              "purple",
              "green",
              "yellow",
              "rose",
              "teal",
              "sky",
              "mint",
              "sand",
              "gray",
              "blueMid",
              "orange",
              "lightgreen",
            ]}
            value={{
              light: "light",
              dark: "dark",
              blue: "blue",
              purple: "purple",
              green: "green",
              yellow: "yellow",
              rose: "rose",
              teal: "teal",
              sky: "sky",
              mint: "mint",
              sand: "sand",
              gray: "gray",
              blueMid: "blueMid",
              orange: "orange",
              lightgreen: "lightgreen",
            }}
          >
            <NuqsAdapter>
              <SimpleNavBAr />
              {children}
            </NuqsAdapter>
            <Toaster />
          </ThemeProvider>
        </QueryProvider>
      </body>
    </html>
  );
}
